=== IsabelVSousa/M0373_pr04/libro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo"></xs:element>
                <xs:element name="escritores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="escritor"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="publicacion"></xs:element>
                <xs:element name="generos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genero"></xs:element>
                            <xs:element name="genero"></xs:element>
                            <xs:element name="genero"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- revisar si cuando hay varios elementos, se hace asi -->

=== IsabelVSousa/M0373_pr04/libro.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Crea un documento XML que contenga información sobre un libro. Crea el XSD asociado que valide
que el XML contiene los siguientes elementos:
o Título(obligatorio, no se puede repetir y debe contener menos de 30 caracteres)
o Escritores (obligatorio y pueden haber uno o más)
o Ediciones (un atributo obligatorio, ha de ser un valor numérico)
o Publicación (obligatorio, único y debe de contener un formato fecha)
o Género(obligatorio, múltiple y solo puede ser: “fantástico”, “histórico”, “terror”, “thriller” o
”humor”)-->

<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="libro.xsd">
    <titulo edicion="15">El señor de los anillos</titulo>
    <escritores>
        <escritor>JRR Tolkien</escritor>
    </escritores>
    <publicacion>1954-06-29</publicacion>
    <generos>
        <genero>Fantastico</genero>
        <genero>Aventura</genero>
        <genero>Romance</genero>
    </generos>
</libro>
